services:
  stremio:
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
      IPADDRESS: 198.7.124.122
    ports:
      - "8080:8080"
      - "11470:11470" 
      - "12470:12470"
    volumes:
      - "/srv/config/stremio/:/root/.stremio-server" 
